# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui_ImageExposure.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1068, 971)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 576))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_1 = QtWidgets.QFrame(self.centralwidget)
        self.frame_1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.frame_1)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.frame_9 = QtWidgets.QFrame(self.frame_1)
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 100))
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_9)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_10 = QtWidgets.QFrame(self.frame_9)
        self.frame_10.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_3.setMaximumSize(QtCore.QSize(200, 30))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_2.addWidget(self.pushButton_3)
        self.pushButton_2 = QtWidgets.QPushButton(self.frame_10)
        self.pushButton_2.setMaximumSize(QtCore.QSize(200, 30))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.gridLayout.addWidget(self.frame_10, 0, 0, 1, 2)
        self.pushButton_5 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_5.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.pushButton_5.setFont(font)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout.addWidget(self.pushButton_5, 1, 1, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_4.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout.addWidget(self.pushButton_4, 1, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frame_9, 4, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(self.frame_1)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.frame_5)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_4 = QtWidgets.QLabel(self.frame_5)
        self.label_4.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_4.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_4.setLineWidth(3)
        self.label_4.setText("")
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 1, 0, 1, 1)
        self.verticalSlider_4 = QtWidgets.QSlider(self.frame_5)
        self.verticalSlider_4.setProperty("value", 50)
        self.verticalSlider_4.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_4.setObjectName("verticalSlider_4")
        self.gridLayout_6.addWidget(self.verticalSlider_4, 1, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame_5)
        self.label_5.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_5.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_5.setLineWidth(3)
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.gridLayout_6.addWidget(self.label_5, 1, 2, 1, 1)
        self.verticalSlider_5 = QtWidgets.QSlider(self.frame_5)
        self.verticalSlider_5.setMouseTracking(False)
        self.verticalSlider_5.setProperty("value", 50)
        self.verticalSlider_5.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_5.setObjectName("verticalSlider_5")
        self.gridLayout_6.addWidget(self.verticalSlider_5, 1, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.frame_5)
        self.label_6.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_6.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_6.setLineWidth(3)
        self.label_6.setText("")
        self.label_6.setObjectName("label_6")
        self.gridLayout_6.addWidget(self.label_6, 1, 4, 1, 1)
        self.verticalSlider_6 = QtWidgets.QSlider(self.frame_5)
        self.verticalSlider_6.setProperty("value", 50)
        self.verticalSlider_6.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_6.setObjectName("verticalSlider_6")
        self.gridLayout_6.addWidget(self.verticalSlider_6, 1, 5, 1, 1)
        self.frame_8 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_8.sizePolicy().hasHeightForWidth())
        self.frame_8.setSizePolicy(sizePolicy)
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.frame_8)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.radioButton_9 = QtWidgets.QRadioButton(self.frame_8)
        self.radioButton_9.setText("")
        self.radioButton_9.setObjectName("radioButton_9")
        self.buttonGroup = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup.setObjectName("buttonGroup")
        self.buttonGroup.addButton(self.radioButton_9)
        self.gridLayout_5.addWidget(self.radioButton_9, 0, 11, 1, 1)
        self.checkBox_6 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox_6.setText("")
        self.checkBox_6.setObjectName("checkBox_6")
        self.buttonGroup_2 = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_2.setObjectName("buttonGroup_2")
        self.buttonGroup_2.addButton(self.checkBox_6)
        self.gridLayout_5.addWidget(self.checkBox_6, 0, 8, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem1, 0, 4, 1, 1)
        self.radioButton_7 = QtWidgets.QRadioButton(self.frame_8)
        self.radioButton_7.setText("")
        self.radioButton_7.setObjectName("radioButton_7")
        self.buttonGroup.addButton(self.radioButton_7)
        self.gridLayout_5.addWidget(self.radioButton_7, 0, 2, 1, 1)
        self.checkBox_5 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox_5.setText("")
        self.checkBox_5.setObjectName("checkBox_5")
        self.buttonGroup_2.addButton(self.checkBox_5)
        self.gridLayout_5.addWidget(self.checkBox_5, 0, 3, 1, 1)
        self.radioButton_8 = QtWidgets.QRadioButton(self.frame_8)
        self.radioButton_8.setText("")
        self.radioButton_8.setObjectName("radioButton_8")
        self.buttonGroup.addButton(self.radioButton_8)
        self.gridLayout_5.addWidget(self.radioButton_8, 0, 5, 1, 1)
        self.checkBox_4 = QtWidgets.QCheckBox(self.frame_8)
        self.checkBox_4.setText("")
        self.checkBox_4.setObjectName("checkBox_4")
        self.buttonGroup_2.addButton(self.checkBox_4)
        self.gridLayout_5.addWidget(self.checkBox_4, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem2, 0, 9, 1, 1)
        self.gridLayout_6.addWidget(self.frame_8, 0, 0, 1, 6)
        self.verticalLayout.addWidget(self.frame_5)
        self.gridLayout_9.addWidget(self.frame_4, 3, 0, 1, 1)
        self.frame_2 = QtWidgets.QFrame(self.frame_1)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.frame_2)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_1 = QtWidgets.QLabel(self.frame_3)
        self.label_1.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_1.setLineWidth(3)
        self.label_1.setText("")
        self.label_1.setObjectName("label_1")
        self.gridLayout_4.addWidget(self.label_1, 1, 0, 1, 1)
        self.verticalSlider_1 = QtWidgets.QSlider(self.frame_3)
        self.verticalSlider_1.setProperty("value", 50)
        self.verticalSlider_1.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_1.setTickPosition(QtWidgets.QSlider.TicksBelow)
        self.verticalSlider_1.setTickInterval(10)
        self.verticalSlider_1.setObjectName("verticalSlider_1")
        self.gridLayout_4.addWidget(self.verticalSlider_1, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setAutoFillBackground(False)
        self.label_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_2.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_2.setLineWidth(3)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_4.addWidget(self.label_2, 1, 2, 1, 1)
        self.verticalSlider_2 = QtWidgets.QSlider(self.frame_3)
        self.verticalSlider_2.setProperty("value", 50)
        self.verticalSlider_2.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_2.setObjectName("verticalSlider_2")
        self.gridLayout_4.addWidget(self.verticalSlider_2, 1, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.label_3.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_3.setLineWidth(3)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.gridLayout_4.addWidget(self.label_3, 1, 4, 1, 1)
        self.verticalSlider_3 = QtWidgets.QSlider(self.frame_3)
        self.verticalSlider_3.setProperty("value", 50)
        self.verticalSlider_3.setOrientation(QtCore.Qt.Vertical)
        self.verticalSlider_3.setObjectName("verticalSlider_3")
        self.gridLayout_4.addWidget(self.verticalSlider_3, 1, 5, 1, 1)
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_7)
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem3, 0, 5, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem4, 0, 1, 1, 1)
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame_7)
        self.radioButton_4.setText("")
        self.radioButton_4.setChecked(True)
        self.radioButton_4.setObjectName("radioButton_4")
        self.buttonGroup.addButton(self.radioButton_4)
        self.gridLayout_3.addWidget(self.radioButton_4, 0, 2, 1, 1)
        self.checkBox_3 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox_3.setText("")
        self.checkBox_3.setObjectName("checkBox_3")
        self.buttonGroup_2.addButton(self.checkBox_3)
        self.gridLayout_3.addWidget(self.checkBox_3, 0, 8, 1, 1)
        self.checkBox_1 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox_1.setText("")
        self.checkBox_1.setObjectName("checkBox_1")
        self.buttonGroup_2.addButton(self.checkBox_1)
        self.gridLayout_3.addWidget(self.checkBox_1, 0, 0, 1, 1)
        self.radioButton_5 = QtWidgets.QRadioButton(self.frame_7)
        self.radioButton_5.setText("")
        self.radioButton_5.setObjectName("radioButton_5")
        self.buttonGroup.addButton(self.radioButton_5)
        self.gridLayout_3.addWidget(self.radioButton_5, 0, 6, 1, 1)
        self.radioButton_6 = QtWidgets.QRadioButton(self.frame_7)
        self.radioButton_6.setText("")
        self.radioButton_6.setObjectName("radioButton_6")
        self.buttonGroup.addButton(self.radioButton_6)
        self.gridLayout_3.addWidget(self.radioButton_6, 0, 12, 1, 1)
        self.checkBox_2 = QtWidgets.QCheckBox(self.frame_7)
        self.checkBox_2.setText("")
        self.checkBox_2.setObjectName("checkBox_2")
        self.buttonGroup_2.addButton(self.checkBox_2)
        self.gridLayout_3.addWidget(self.checkBox_2, 0, 4, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem5, 0, 9, 1, 1)
        self.gridLayout_4.addWidget(self.frame_7, 0, 0, 1, 6)
        self.gridLayout_10.addWidget(self.frame_3, 0, 0, 1, 1)
        self.gridLayout_9.addWidget(self.frame_2, 2, 0, 1, 1)
        self.frame_6 = QtWidgets.QFrame(self.frame_1)
        self.frame_6.setMaximumSize(QtCore.QSize(16777215, 50))
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.frame_6)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.pushButton_1 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_1.setMaximumSize(QtCore.QSize(200, 30))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setObjectName("pushButton_1")
        self.gridLayout_11.addWidget(self.pushButton_1, 0, 0, 1, 1)
        self.radioButton_1 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_1.setChecked(True)
        self.radioButton_1.setObjectName("radioButton_1")
        self.gridLayout_11.addWidget(self.radioButton_1, 0, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem6, 0, 4, 1, 1)
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_2.setChecked(False)
        self.radioButton_2.setObjectName("radioButton_2")
        self.gridLayout_11.addWidget(self.radioButton_2, 0, 2, 1, 1)
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame_6)
        self.radioButton_3.setObjectName("radioButton_3")
        self.gridLayout_11.addWidget(self.radioButton_3, 0, 3, 1, 1)
        self.lcdNumber = QtWidgets.QLCDNumber(self.frame_6)
        self.lcdNumber.setLineWidth(0)
        self.lcdNumber.setObjectName("lcdNumber")
        self.gridLayout_11.addWidget(self.lcdNumber, 0, 8, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame_6)
        self.label_8.setMaximumSize(QtCore.QSize(31, 50))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap(":/Images/logo2.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.gridLayout_11.addWidget(self.label_8, 0, 9, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.frame_6)
        self.pushButton_7.setMinimumSize(QtCore.QSize(150, 30))
        self.pushButton_7.setDefault(True)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_11.addWidget(self.pushButton_7, 0, 7, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame_6)
        self.label_7.setMinimumSize(QtCore.QSize(120, 30))
        self.label_7.setFrameShape(QtWidgets.QFrame.Box)
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_11.addWidget(self.label_7, 0, 5, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame_6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_9.setTextFormat(QtCore.Qt.AutoText)
        self.label_9.setScaledContents(True)
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setWordWrap(True)
        self.label_9.setObjectName("label_9")
        self.gridLayout_11.addWidget(self.label_9, 0, 6, 1, 1)
        self.gridLayout_9.addWidget(self.frame_6, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_1, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1068, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_3.setText(_translate("MainWindow", "Previous Set"))
        self.pushButton_2.setText(_translate("MainWindow", "Next Set"))
        self.pushButton_5.setToolTip(_translate("MainWindow", "Click to go to next page"))
        self.pushButton_5.setText(_translate("MainWindow", "Next"))
        self.pushButton_4.setText(_translate("MainWindow", "Back"))
        self.pushButton_1.setToolTip(_translate("MainWindow", "Show the first set of images"))
        self.pushButton_1.setText(_translate("MainWindow", "Show Images"))
        self.radioButton_1.setText(_translate("MainWindow", "Brightness"))
        self.radioButton_2.setText(_translate("MainWindow", "Contrast"))
        self.radioButton_3.setText(_translate("MainWindow", "Sharpness"))
        self.pushButton_7.setText(_translate("MainWindow", "None Selected"))
        self.label_7.setText(_translate("MainWindow", "Press Here to Select"))
        self.label_9.setText(_translate("MainWindow", ">>>"))

import icons_ImageCrop_rc
